{application,con_cache,
             [{description,"ETS based key-value storage with support for row-level isolated writes, TTL auto-purge, and modification callbacks."},
              {modules,['Elixir.ConCache','Elixir.ConCache.Application',
                        'Elixir.ConCache.Item','Elixir.ConCache.Lock',
                        'Elixir.ConCache.Lock.Monitors',
                        'Elixir.ConCache.Lock.Resource',
                        'Elixir.ConCache.LockSupervisor',
                        'Elixir.ConCache.Operations','Elixir.ConCache.Owner']},
              {registered,[]},
              {vsn,"0.12.1"},
              {applications,[kernel,stdlib,elixir,logger]},
              {mod,{'Elixir.ConCache.Application',[]}}]}.
